### ISSUE TITLE
Book not linking to correct binderhub_url

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/t1_book#12]
FYI @ltetrel – I saw that you changed the `binderhub_url` from MyBinder to the NeuroLibre Binderhub in commit 53ca527a64c41110893b60f63d5ac4d03f79ece6. However, if you go to the Jupyter Book [here](http://qmrlab.org/t1_book/intro) and click on Launch Binder, it still sends you to MyBinder, not the NeuroLibre Binderhub.

**Comment by ltetrel** [comment]
This is normal, I (re) changed to mybinder since we have issues with the allocation on CC
