### ISSUE TITLE
JupyterLab not opening the notebook automatically

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/t1_book#14]
Not sure why - maybe something internal changed with how JupyterLab and MyBinder interact.

To test out, go here (http://qmrlab.org/t1_book/01/ir_blog/IR_SignalModelling.html) and click the Binder button.

@zelenkastiot @FilipVel @agahkarakuzu @TommyBoshkovski have you ever experienced this? Any clue why?

Note that I'm on an older version of JupyterBook (~0.3 I think) and am not willing to upgrade right now.

**Comment by mathieuboudreau** [comment]
Ok so it's working for one of @zelenkastiot's books (https://mybinder.org/v2/gh/Notebook-Factory/NeuralDecoding_book/master?urlpath=lab/tree/content%2F03%2Fsubsection%2F01-03%2Fsos_notebook1.ipynb), just not mine? Hmm

**Comment by zelenkastiot** [comment]
https://github.com/qMRLab/t1_book/pull/15

**Comment by mathieuboudreau** [comment]
Resolved by #15, thank you @zelenkastiot !!!
